export const
    ADD_TASK = 'ADD_TASK',
    REMOVE_TASK = 'REMOVE_TASK',

    REMOVE_SELECTED_TASKS = 'REMOVE_SELECTED_TASKS',
    SELECT_ALL_TASKS = 'SELECT_ALL_TASKS',

    CHANGE_STATUS = 'CHANGE_STATUS',
    CHANGE_RADIO_BUTTON = 'CHANGE_RADIO_BUTTON',

    SHOW_COUNT_TASKS = 'SHOW_COUNT_TASKS',

    SEARCH_TASKS = 'SEARCH_TASKS',
    SUBSTRING_VALUE = 'SUBSTRING_VALUE';